### ISSUE TITLE
Failed to activate the code-shadow package

### ISSUE THREAD

**Issue by rootasjey** [AliShug/code-shadow#7]
Hello, thanks for this package which looks promising.
But I've an issue when activating the package for the 1st time.

[Enter steps to reproduce:]

1. ...Install the code-shadow package from the Atom's settings view
2. ...Restart Atom

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [code-shadow](https://github.com/AliShug/code-shadow) package 0.1.0

### Stack Trace

Failed to activate the code-shadow package

```
At editor.displayLayer.onDidChangeSync is not a function

TypeError: editor.displayLayer.onDidChangeSync is not a function
    at /packages/code-shadow/lib/code-shadow-view.js:157:48)
    at /packages/code-shadow/lib/code-shadow.js:20:23
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.24.0/resources/app/src/workspace.js:728:15)
    at Object.activate (/packages/code-shadow/lib/code-shadow.js:19:43)
    at Package.activateNow (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:200:20)
    at Package.activate (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.24.0/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.24.0/resources/app/src/atom-environment.js:841:27)
```

### Commands

```
     -2:31.3.0 tool-bar:position-left (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
animated-page-scroll 1.2.0 
atom-beautify 0.30.9 
atom-bracket-highlight 0.3.2 
atom-css-comb 3.3.1 
atom-ide-ui 0.9.1 
atom-jasmine 0.9.1 
atom-material-syntax 1.0.8 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-ternjs 0.18.3 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
chester-atom-syntax 0.3.0 
chestnut-light-atom-syntax 0.2.1 
click-link 1.0.11 
code-peek 1.4.21 
code-shadow 0.1.0 
cursor-scroll 1.0.1 
eclectic-syntax 0.3.0 
emerald-dream-syntax 0.2.3 
fairygloss 0.4.0 
ficus-syntax 2.1.0 
file-icons 2.1.17 
firewatch-syntax 1.1.1 
flat-ui-syntax 0.5.1 
flatwhite-syntax 0.8.1 
folded-code-preview 0.2.5 
github-atom-dark-syntax 0.5.0 
github-atom-light-syntax 0.5.0 
gloom 0.6.5 
goto-definition 1.3.4 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-typescript 0.7.2 
indent-guide-improved 1.4.13 
intentions 1.1.5 
js-refactor 0.7.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.6.10 
minimap 4.29.8 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
monokai 0.24.0 
nord-atom-syntax 0.9.1 
oceanic-next 1.0.0 
oceanic-reef-syntax 0.9.0 
outline-selection 0.3.2 
package-sync 1.1.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
pure-syntax 0.3.0 
rain-syntax 2.1.2 
refactor 0.11.5 
remember-folds 0.3.0 
scm 1.7.3 
snippet-generator 0.3.2 
styri-syntax 0.2.0 
teletype 0.8.0 
title-bar-replacer 1.8.1 
todo-show 2.2.0 
tool-bar 1.1.6 
```

Thanks in advance.

**Comment by CRY-D** [comment]
the same Issue 
**Atom 1.34.X64 on linuxMint**
